import {
  LETTER_WIDTH_PX,
  LETTER_PADDING_PX,
  type DocumentTemplate,
  type HeadingWidget,
  type SenderInfoWidget,
  type RecipientInfoWidget,
  type DataTableWidget,
  type SummarySectionWidget,
  type DateBlockWidget,
  type DetailsBlockWidget,
  type NoteWidget,
  type DividerWidget,
  type TextWidget,
  type LogoWidget,
} from "./types";

const W = LETTER_WIDTH_PX;
const P = LETTER_PADDING_PX;
const CW = W - P * 2; // content width

// ============================================================================
// Invoice Template Preset
// ============================================================================

export function createInvoiceTemplate(): DocumentTemplate {
  const now = new Date().toISOString();
  return {
    version: 1,
    paperSize: "letter",
    theme: {
      primaryColor: "#1a1a2e",
      accentColor: "#16213e",
      backgroundColor: "#ffffff",
      fontFamily: "Inter",
      baseFontSize: 12,
    },
    widgets: [
      {
        id: "topBar",
        type: "divider",
        position: { x: 0, y: 0, width: W, height: 10 },
        visible: true,
        color: "#1a1a2e",
        thickness: 10,
        style: "solid",
      } satisfies DividerWidget,
      {
        id: "heading",
        type: "heading",
        position: { x: P, y: 28, width: 530, height: 56 },
        visible: true,
        text: "INVOICE",
        fontSize: 36,
        fontWeight: "bold",
        color: "#a3a3a3",
        align: "left",
      } satisfies HeadingWidget,
      {
        id: "senderInfo",
        type: "senderInfo",
        position: { x: P, y: 100, width: 300, height: 180 },
        visible: true,
        showName: true,
        showPhone: true,
        showEmail: true,
        showField1: true,
        showField2: true,
        showField3: true,
        showAddress: false,
        fontSize: 10,
        color: "#333333",
        fontWeight: "normal",
      } satisfies SenderInfoWidget,
      {
        id: "detailsBlock",
        type: "detailsBlock",
        position: { x: 428, y: 100, width: 340, height: 120 },
        visible: true,
        label: "Details",
        showField1: true,
        showField2: true,
        showField3: false,
        showField4: true,
        showField5: false,
        fontSize: 10,
        color: "#333333",
        labelColor: "#1a1a2e",
      } satisfies DetailsBlockWidget,
      {
        id: "recipientInfo",
        type: "recipientInfo",
        position: { x: 428, y: 220, width: 340, height: 100 },
        visible: true,
        label: "Bill To",
        showName: true,
        showAddress: true,
        fontSize: 10,
        color: "#333333",
        labelColor: "#1a1a2e",
        fontWeight: "normal",
      } satisfies RecipientInfoWidget,
      {
        id: "amountLabel",
        type: "text",
        position: { x: P, y: 340, width: 200, height: 28 },
        visible: true,
        content: "Amount Details",
        fontSize: 14,
        color: "#1a1a2e",
        fontWeight: "bold",
        fontStyle: "normal",
        align: "left",
        lineHeight: 1.4,
        backgroundColor: "transparent",
        padding: 0,
      } satisfies TextWidget,
      {
        id: "dataTable",
        type: "dataTable",
        position: { x: P, y: 375, width: CW, height: 280 },
        visible: true,
        columns: [],
        customRows: [],
        sections: [
          {
            id: "lineItems",
            title: "Line Items",
            columns: [
              { id: "desc", label: "Products/Services", align: "left" },
              { id: "qty", label: "Qty", align: "right" },
              { id: "cost", label: "Cost", align: "right" },
              { id: "total", label: "Total", align: "right" },
            ],
            rows: [],
          },
        ],
        showSubtotals: false,
        headerBgColor: "#f7f5f2",
        headerTextColor: "#1a1a2e",
        rowTextColor: "#333333",
        totalBgColor: "#f5f5f5",
        totalTextColor: "#1a1a2e",
        borderColor: "#e5e5e5",
        fontSize: 11,
      } satisfies DataTableWidget,
      {
        id: "note",
        type: "note",
        position: { x: P, y: 680, width: 200, height: 100 },
        visible: true,
        label: "Note",
        showLabel: true,
        fontSize: 10,
        color: "#555555",
        bgColor: "transparent",
        showBg: false,
        borderRadius: 0,
      } satisfies NoteWidget,
      {
        id: "summarySection",
        type: "summarySection",
        position: { x: 300, y: 680, width: 468, height: 100 },
        visible: true,
        fontSize: 11,
        textColor: "#1a1a2e",
        totalTextColor: "#1a1a2e",
        borderColor: "#1a1a2e",
      } satisfies SummarySectionWidget,
      {
        id: "logo",
        type: "logo",
        position: { x: W - P - 120, y: 36, width: 120, height: 56 },
        visible: true,
        objectFit: "contain",
        borderRadius: 4,
      } satisfies LogoWidget,
      {
        id: "dateBlock",
        type: "dateBlock",
        position: { x: P, y: 96, width: 280, height: 24 },
        visible: false,
        label: "Date:",
        showLabel: true,
        format: "long",
        fontSize: 11,
        color: "#666666",
        fontWeight: "normal",
        align: "left",
      } satisfies DateBlockWidget,
    ],
    createdAt: now,
    updatedAt: now,
  };
}

// ============================================================================
// Estimate Template Preset
// ============================================================================

export function createEstimateTemplate(): DocumentTemplate {
  const now = new Date().toISOString();
  return {
    version: 1,
    paperSize: "letter",
    theme: {
      primaryColor: "#1a1a2e",
      accentColor: "#16213e",
      backgroundColor: "#ffffff",
      fontFamily: "Inter",
      baseFontSize: 12,
    },
    widgets: [
      {
        id: "heading",
        type: "heading",
        position: { x: P, y: P, width: 280, height: 60 },
        visible: true,
        text: "ESTIMATE",
        fontSize: 32,
        fontWeight: "bold",
        color: "#1a1a2e",
        align: "left",
      } satisfies HeadingWidget,
      {
        id: "logo",
        type: "logo",
        position: { x: W - P - 120, y: P, width: 120, height: 70 },
        visible: true,
        objectFit: "contain",
        borderRadius: 4,
      } satisfies LogoWidget,
      {
        id: "dateBlock",
        type: "dateBlock",
        position: { x: P, y: P + 72, width: 280, height: 30 },
        visible: true,
        label: "Date:",
        showLabel: true,
        format: "long",
        fontSize: 11,
        color: "#666666",
        fontWeight: "normal",
        align: "left",
      } satisfies DateBlockWidget,
      {
        id: "divider1",
        type: "divider",
        position: { x: P, y: P + 116, width: CW, height: 2 },
        visible: true,
        color: "#1a1a2e",
        thickness: 2,
        style: "solid",
      } satisfies DividerWidget,
      {
        id: "senderInfo",
        type: "senderInfo",
        position: { x: P, y: P + 132, width: 260, height: 110 },
        visible: true,
        showName: true,
        showPhone: true,
        showEmail: true,
        showField1: true,
        showField2: true,
        showField3: true,
        showAddress: false,
        fontSize: 11,
        color: "#333333",
        fontWeight: "normal",
      } satisfies SenderInfoWidget,
      {
        id: "recipientInfo",
        type: "recipientInfo",
        position: { x: W - P - 260, y: P + 132, width: 260, height: 110 },
        visible: true,
        label: "Estimate For:",
        showName: true,
        showAddress: true,
        fontSize: 11,
        color: "#333333",
        labelColor: "#1a1a2e",
        fontWeight: "normal",
      } satisfies RecipientInfoWidget,
      {
        id: "detailsBlock",
        type: "detailsBlock",
        position: { x: P, y: P + 260, width: CW, height: 80 },
        visible: true,
        label: "Details",
        showField1: true,
        showField2: true,
        showField3: false,
        showField4: false,
        showField5: false,
        fontSize: 11,
        color: "#333333",
        labelColor: "#1a1a2e",
      } satisfies DetailsBlockWidget,
      {
        id: "dataTable",
        type: "dataTable",
        position: { x: P, y: P + 360, width: CW, height: 120 },
        visible: true,
        columns: [
          { id: "col_desc", label: "Description", align: "left" },
          { id: "col_amount", label: "Amount", align: "right" },
        ],
        customRows: [],
        headerBgColor: "#1a1a2e",
        headerTextColor: "#ffffff",
        rowTextColor: "#333333",
        totalBgColor: "#f5f5f5",
        totalTextColor: "#1a1a2e",
        borderColor: "#e5e5e5",
        fontSize: 12,
      } satisfies DataTableWidget,
      {
        id: "note",
        type: "note",
        position: { x: P, y: P + 500, width: CW, height: 100 },
        visible: true,
        label: "Notes",
        showLabel: true,
        fontSize: 11,
        color: "#555555",
        bgColor: "#f9f9f9",
        showBg: true,
        borderRadius: 6,
      } satisfies NoteWidget,
    ],
    createdAt: now,
    updatedAt: now,
  };
}

// ============================================================================
// Blank Template
// ============================================================================

export function createBlankTemplate(): DocumentTemplate {
  const now = new Date().toISOString();
  return {
    version: 1,
    paperSize: "letter",
    theme: {
      primaryColor: "#1a1a2e",
      accentColor: "#16213e",
      backgroundColor: "#ffffff",
      fontFamily: "Inter",
      baseFontSize: 12,
    },
    widgets: [
      {
        id: "heading",
        type: "heading",
        position: { x: P, y: P, width: 300, height: 48 },
        visible: true,
        text: "DOCUMENT",
        fontSize: 28,
        fontWeight: "bold",
        color: "#1a1a2e",
        align: "left",
      } satisfies HeadingWidget,
    ],
    createdAt: now,
    updatedAt: now,
  };
}
